# Generated by Django 5.2.3 on 2025-06-21 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('mail_messages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Начало рассылки')),
                ('end_time', models.DateTimeField(verbose_name='Окончание рассылки')),
                ('status', models.CharField(choices=[('CREATED', 'Создана'), ('STARTED', 'Запущена'), ('FINISHED', 'Завершена')], default='CREATED', max_length=10)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mail_messages.message')),
                ('recipients', models.ManyToManyField(to='clients.client')),
            ],
        ),
    ]
